server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false   # server se ne registruje sam kod sebe
    fetch-registry: false          # ne povla?i registry
  server:
    enable-self-preservation: false   # opcionalno, za development
